<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Table users
        DB::table('users')->insert([
        [ // Administrator 1
            // 'id' => 1,
            'nama' => 'Administrator 1',
            'role' => 'Administrator',
            'username' => 'administrator1',
            'password' => Hash::make('password'),
            'email' => 'Administrator1@gmail.com',
            'foto' => 'http://lorempixel.com/500/500/',
            'no_hp' => '081234567891',
            'fingerprint_pin' => '1231',
            'remember_token' => Str::random(10),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Administrator 2
            // 'id' => 2,
            'nama' => 'Administrator 2',
            'role' => 'Administrator',
            'username' => 'administrator2',
            'password' => Hash::make('password'),
            'email' => 'administrator2@gmail.com',
            'foto' => 'http://lorempixel.com/500/500/',
            'no_hp' => '081234567892',
            'fingerprint_pin' => '1232',
            'remember_token' => Str::random(10),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Dosen 1
            // 'id' => 3,
            'nama' => 'Dosen 1',
            'role' => 'Dosen',
            'username' => 'dosen1',
            'password' => Hash::make('password'),
            'email' => 'dosen1@gmail.com',
            'foto' => 'http://lorempixel.com/500/500/',
            'no_hp' => '081234567893',
            'fingerprint_pin' => '1233',
            'remember_token' => Str::random(10),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Dosen 2
            // 'id' => 4,
            'nama' => 'Dosen 2',
            'role' => 'Dosen',
            'username' => 'dosen2',
            'password' => Hash::make('password'),
            'email' => 'dosen2@gmail.com',
            'foto' => 'http://lorempixel.com/500/500/',
            'no_hp' => '081234567894',
            'fingerprint_pin' => '1234',
            'remember_token' => Str::random(10),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Scrum Master 1
            // 'id' => 5,
            'nama' => 'Scrum Master 1',
            'role' => 'Scrum Master',
            'username' => 'scrummaster1',
            'password' => Hash::make('password'),
            'email' => 'scrummaster1@gmail.com',
            'foto' => 'http://lorempixel.com/500/500/',
            'no_hp' => '081234567895',
            'fingerprint_pin' => '1235',
            'remember_token' => Str::random(10),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Scrum Master 2
            // 'id' => 6,
            'nama' => 'Scrum Master 2',
            'role' => 'Scrum Master',
            'username' => 'scrummaster2',
            'password' => Hash::make('password'),
            'email' => 'scrummaster2@gmail.com',
            'foto' => 'http://lorempixel.com/500/500/',
            'no_hp' => '081234567896',
            'fingerprint_pin' => '1236',
            'remember_token' => Str::random(10),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Product Owner 1
            // 'id' => 7,
            'nama' => 'Product Owner 1',
            'role' => 'Product Owner',
            'username' => 'productowner1',
            'password' => Hash::make('password'),
            'email' => 'productowner1@gmail.com',
            'foto' => 'http://lorempixel.com/500/500/',
            'no_hp' => '081234567897',
            'fingerprint_pin' => '1237',
            'remember_token' => Str::random(10),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Product Owner 2
            // 'id' => 8,
            'nama' => 'Product Owner 2',
            'role' => 'Product Owner',
            'username' => 'productowner2',
            'password' => Hash::make('password'),
            'email' => 'productowner2@gmail.com',
            'foto' => 'http://lorempixel.com/500/500/',
            'no_hp' => '081234567898',
            'fingerprint_pin' => '1238',
            'remember_token' => Str::random(10),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Mahasiswa 1
            // 'id' => 9,
            'nama' => 'Mahasiswa 1',
            'role' => 'Mahasiswa',
            'username' => 'mahasiswa1',
            'password' => Hash::make('password'),
            'email' => 'mahasiswa1@gmail.com',
            'foto' => 'http://lorempixel.com/500/500/',
            'no_hp' => '081234567899',
            'fingerprint_pin' => '1239',
            'remember_token' => Str::random(10),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Mahasiswa 2
            // 'id' => 10,
            'nama' => 'Mahasiswa 2',
            'role' => 'Mahasiswa',
            'username' => 'mahasiswa2',
            'password' => Hash::make('password'),
            'email' => 'mahasiswa2@gmail.com',
            'foto' => 'http://lorempixel.com/500/500/',
            'no_hp' => '081234567890',
            'fingerprint_pin' => '1230',
            'remember_token' => Str::random(10),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Mahasiswa 3
            // 'id' => 11,
            'nama' => 'Mahasiswa 3',
            'role' => 'Mahasiswa',
            'username' => 'mahasiswa3',
            'password' => Hash::make('password'),
            'email' => 'mahasiswa3@gmail.com',
            'foto' => 'http://lorempixel.com/500/500/',
            'no_hp' => '082234567891',
            'fingerprint_pin' => '2231',
            'remember_token' => Str::random(10),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Mahasiswa 4
            // 'id' => 12,
            'nama' => 'Mahasiswa 4',
            'role' => 'Mahasiswa',
            'username' => 'mahasiswa4',
            'password' => Hash::make('password'),
            'email' => 'mahasiswa4@gmail.com',
            'foto' => 'http://lorempixel.com/500/500/',
            'no_hp' => '082234567892',
            'fingerprint_pin' => '2232',
            'remember_token' => Str::random(10),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Mahasiswa 5
            // 'id' => 13,
            'nama' => 'Mahasiswa 5',
            'role' => 'Mahasiswa',
            'username' => 'mahasiswa5',
            'password' => Hash::make('password'),
            'email' => 'mahasiswa5@gmail.com',
            'foto' => 'http://lorempixel.com/500/500/',
            'no_hp' => '082234567893',
            'fingerprint_pin' => '2233',
            'remember_token' => Str::random(10),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Mahasiswa 6
            // 'id' => 14,
            'nama' => 'Mahasiswa 6',
            'role' => 'Mahasiswa',
            'username' => 'mahasiswa6',
            'password' => Hash::make('password'),
            'email' => 'mahasiswa6@gmail.com',
            'foto' => 'http://lorempixel.com/500/500/',
            'no_hp' => '082234567894',
            'fingerprint_pin' => '2234',
            'remember_token' => Str::random(10),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Mahasiswa 7
            // 'id' => 15,
            'nama' => 'Mahasiswa 7',
            'role' => 'Mahasiswa',
            'username' => 'mahasiswa7',
            'password' => Hash::make('password'),
            'email' => 'mahasiswa7@gmail.com',
            'foto' => 'http://lorempixel.com/500/500/',
            'no_hp' => '082234567895',
            'fingerprint_pin' => '2235',
            'remember_token' => Str::random(10),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Mahasiswa 8
            // 'id' => 16,
            'nama' => 'Mahasiswa 8',
            'role' => 'Mahasiswa',
            'username' => 'mahasiswa8',
            'password' => Hash::make('password'),
            'email' => 'mahasiswa8@gmail.com',
            'foto' => 'http://lorempixel.com/500/500/',
            'no_hp' => '082234567896',
            'fingerprint_pin' => '2236',
            'remember_token' => Str::random(10),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Mahasiswa 9
            // 'id' => 17,
            'nama' => 'Mahasiswa 9',
            'role' => 'Mahasiswa',
            'username' => 'mahasiswa9',
            'password' => Hash::make('password'),
            'email' => 'mahasiswa9@gmail.com',
            'foto' => 'http://lorempixel.com/500/500/',
            'no_hp' => '0822345678967',
            'fingerprint_pin' => '2237',
            'remember_token' => Str::random(10),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Mahasiswa 10
            // 'id' => 18,
            'nama' => 'Mahasiswa 10',
            'role' => 'Mahasiswa',
            'username' => 'mahasiswa10',
            'password' => Hash::make('password'),
            'email' => 'mahasiswa10@gmail.com',
            'foto' => 'http://lorempixel.com/500/500/',
            'no_hp' => '0822345678968',
            'fingerprint_pin' => '2238',
            'remember_token' => Str::random(10),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]]);
    }
}
